"""OBJ UV Diff (CEM Debug Tool)

Compare UV layout between two Wavefront `.obj` files.
This tool is designed for validating that a generated/imported model matches a
reference export (typically Blockbench) by comparing per-cuboid face UV rectangles
and corner assignment.

It matches objects by their rounded vertex signature (not by name), then reports:
- Missing/mismatched cuboids
- Per-face UV-rect mismatches
- Per-face corner mapping mismatches (mirrored/rotated UVs)

TOOLSGROUP::CEM
SORTGROUP::7
SORTPRIORITY::72
STATUS::active
VERSION::20260308


Expected inputs
- `--ours`: OBJ generated by our pipeline
- `--bb`: OBJ exported by Blockbench (or other reference)

Outputs
- Prints summary and mismatched faces to stdout
- Exit code:
  - 0 if no mismatches
  - 1 if mismatches were found

Usage
- Simple:
  python DEV/cem_obj_uv_diff.py --ours ours.obj --bb ref.obj

- Project example:
  python DEV/cem_obj_uv_diff.py \
    --ours RESOURCEPACK/00_OBORO_20260217/assets/minecraft/optifine/cem/iron_golem.obj \
    --bb RESOURCEPACK/00_OBORO_20260217/assets/minecraft/optifine/cem/iron_golem_fromblockbench.obj
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Set, Tuple


EPS_POS_DEFAULT = 1e-6
EPS_UV_DEFAULT = 2e-5


@dataclass(frozen=True)
class ObjObject:
    name: str
    faces: List[List[Tuple[int, int]]]
    vertex_sig: Tuple[Tuple[float, float, float], ...]
    bbox: Tuple[float, float, float, float, float, float]


@dataclass(frozen=True)
class ObjData:
    vs: List[Tuple[float, float, float]]
    vts: List[Tuple[float, float]]
    objects: List[ObjObject]


def _r6(x: float) -> float:
    return round(float(x), 6)


def _parse_obj(path: Path) -> ObjData:
    vs: List[Tuple[float, float, float]] = [(0.0, 0.0, 0.0)]
    vts: List[Tuple[float, float]] = [(0.0, 0.0)]

    objects_raw: List[dict] = []
    cur = None

    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue

            if line.startswith("o "):
                cur = {"name": line[2:].strip(), "faces": []}
                objects_raw.append(cur)
                continue

            if line.startswith("v "):
                if cur is None:
                    cur = {"name": "__default__", "faces": []}
                    objects_raw.append(cur)
                x, y, z = map(float, line.split()[1:4])
                vs.append((x, y, z))
                continue

            if line.startswith("vt "):
                if cur is None:
                    cur = {"name": "__default__", "faces": []}
                    objects_raw.append(cur)
                u, v = map(float, line.split()[1:3])
                vts.append((u, v))
                continue

            if line.startswith("f "):
                if cur is None:
                    cur = {"name": "__default__", "faces": []}
                    objects_raw.append(cur)
                face: List[Tuple[int, int]] = []
                for p in line.split()[1:]:
                    ss = p.split("/")
                    vi = int(ss[0])
                    vti = int(ss[1]) if len(ss) > 1 and ss[1] else 0
                    face.append((vi, vti))
                cur["faces"].append(face)
                continue

    objects: List[ObjObject] = []
    for o in objects_raw:
        faces: List[List[Tuple[int, int]]] = list(o.get("faces") or [])
        used: Set[int] = set()
        for face in faces:
            for vi, _ in face:
                used.add(int(vi))

        if not used:
            continue

        verts = [vs[i] for i in sorted(used)]
        xs = [v[0] for v in verts]
        ys = [v[1] for v in verts]
        zs = [v[2] for v in verts]

        vertex_sig = tuple(sorted((_r6(v[0]), _r6(v[1]), _r6(v[2])) for v in verts))

        bb = (
            _r6(min(xs)),
            _r6(min(ys)),
            _r6(min(zs)),
            _r6(max(xs)),
            _r6(max(ys)),
            _r6(max(zs)),
        )
        objects.append(ObjObject(name=str(o.get("name") or ""), faces=faces, vertex_sig=vertex_sig, bbox=bb))

    return ObjData(vs=vs, vts=vts, objects=objects)


def _face_side_label(*, vs: List[Tuple[float, float, float]], bbox: Tuple[float, ...], face: List[Tuple[int, int]], eps_pos: float) -> str:
    pts = [vs[vi] for vi, _ in face]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    zs = [p[2] for p in pts]
    xmin, ymin, zmin, xmax, ymax, zmax = bbox

    if max(xs) - min(xs) < eps_pos:
        return "+x" if abs(xs[0] - xmax) < 1e-5 else "-x"
    if max(ys) - min(ys) < eps_pos:
        return "+y" if abs(ys[0] - ymax) < 1e-5 else "-y"
    if max(zs) - min(zs) < eps_pos:
        return "+z" if abs(zs[0] - zmax) < 1e-5 else "-z"
    return "??"


def _uv_bounds(vts: List[Tuple[float, float]], face: List[Tuple[int, int]]) -> Tuple[float, float, float, float]:
    uvs = [vts[vti] for _, vti in face]
    us = [u for u, _ in uvs]
    vs_ = [v for _, v in uvs]
    return (min(us), min(vs_), max(us), max(vs_))


def _corner_index_from_uv(uv: Tuple[float, float], bounds: Tuple[float, float, float, float]) -> int:
    u, v = uv
    umin, vmin, umax, vmax = bounds

    left = abs(u - umin) <= abs(u - umax)
    bottom = abs(v - vmin) <= abs(v - vmax)

    # 0=bl, 1=br, 2=tr, 3=tl
    if left and bottom:
        return 0
    if (not left) and bottom:
        return 1
    if (not left) and (not bottom):
        return 2
    return 3


def _bounds_close(a: Tuple[float, float, float, float], b: Tuple[float, float, float, float], eps_uv: float) -> bool:
    return all(abs(x - y) <= eps_uv for x, y in zip(a, b))


def _uv_close(a: Tuple[float, float], b: Tuple[float, float], eps_uv: float) -> bool:
    return abs(a[0] - b[0]) <= eps_uv and abs(a[1] - b[1]) <= eps_uv


def _compare_objects(
    *,
    ours: ObjData,
    bb: ObjData,
    eps_pos: float,
    eps_uv: float,
    max_cuboid_print: int,
) -> int:
    ours_by = {o.vertex_sig: o for o in ours.objects}
    bb_by = {o.vertex_sig: o for o in bb.objects}
    keys = sorted(set(ours_by) & set(bb_by))

    print(f"matched_cuboids={len(keys)} missing_in_ours={len(set(bb_by) - set(ours_by))} missing_in_bb={len(set(ours_by) - set(bb_by))}")

    mismatched_faces = 0
    rect_mismatch = 0
    corner_mismatch = 0

    printed = 0

    for k in keys:
        oo = ours_by[k]
        bo = bb_by[k]

        ours_faces_by_side: Dict[str, List[Tuple[Tuple[float, float, float], Tuple[float, float]]]] = {}
        bb_faces_by_side: Dict[str, List[Tuple[Tuple[float, float, float], Tuple[float, float]]]] = {}

        # Build per-side mapping from vertex position -> uv
        for face in oo.faces:
            side = _face_side_label(vs=ours.vs, bbox=oo.bbox, face=face, eps_pos=eps_pos)
            ours_faces_by_side.setdefault(side, [])
            for vi, vti in face:
                ours_faces_by_side[side].append((ours.vs[vi], ours.vts[vti]))

        for face in bo.faces:
            side = _face_side_label(vs=bb.vs, bbox=bo.bbox, face=face, eps_pos=eps_pos)
            bb_faces_by_side.setdefault(side, [])
            for vi, vti in face:
                bb_faces_by_side[side].append((bb.vs[vi], bb.vts[vti]))

        bad: List[str] = []
        for side in ["-x", "+x", "-y", "+y", "-z", "+z"]:
            if side not in ours_faces_by_side or side not in bb_faces_by_side:
                continue

            # Reconstruct the 4-vert face list for bounds calculation.
            # We can just use the UVs present for the 4 corners.
            # (We expect 4 entries; if not, skip.)
            ours_uvs = [uv for _, uv in ours_faces_by_side[side]]
            bb_uvs = [uv for _, uv in bb_faces_by_side[side]]
            if len(ours_uvs) != 4 or len(bb_uvs) != 4:
                continue

            ours_bounds = (min(u for u, _ in ours_uvs), min(v for _, v in ours_uvs), max(u for u, _ in ours_uvs), max(v for _, v in ours_uvs))
            bb_bounds = (min(u for u, _ in bb_uvs), min(v for _, v in bb_uvs), max(u for u, _ in bb_uvs), max(v for _, v in bb_uvs))

            if not _bounds_close(ours_bounds, bb_bounds, eps_uv):
                mismatched_faces += 1
                rect_mismatch += 1
                bad.append(f"{side}: rect ours={tuple(_r6(x) for x in ours_bounds)} bb={tuple(_r6(x) for x in bb_bounds)}")
                continue

            # Same rect: compare corner assignment by classifying each vertex uv into corner index.
            ours_corner_counts = [0, 0, 0, 0]
            bb_corner_counts = [0, 0, 0, 0]
            for uv in ours_uvs:
                ours_corner_counts[_corner_index_from_uv(uv, ours_bounds)] += 1
            for uv in bb_uvs:
                bb_corner_counts[_corner_index_from_uv(uv, bb_bounds)] += 1

            # If bounds are same, both should have one of each corner; if not, something is degenerate.
            if ours_corner_counts != [1, 1, 1, 1] or bb_corner_counts != [1, 1, 1, 1]:
                continue

            # Compare mapping by comparing the multiset of UV points at each corner.
            def corner_uvs(uvs: List[Tuple[float, float]], bounds: Tuple[float, float, float, float]) -> List[Tuple[float, float]]:
                out = [(-999.0, -999.0)] * 4
                for uv in uvs:
                    out[_corner_index_from_uv(uv, bounds)] = uv
                return out

            ours_c = corner_uvs(ours_uvs, ours_bounds)
            bb_c = corner_uvs(bb_uvs, bb_bounds)

            # Same bounds but different corner UVs means mirrored/rotated.
            if any(not _uv_close(ours_c[i], bb_c[i], eps_uv) for i in range(4)):
                mismatched_faces += 1
                corner_mismatch += 1
                bad.append(
                    f"{side}: corners ours={tuple(( _r6(u), _r6(v)) for u,v in ours_c)} bb={tuple(( _r6(u), _r6(v)) for u,v in bb_c)}"
                )

        if bad and (max_cuboid_print < 0 or printed < max_cuboid_print):
            printed += 1
            print(f"\nCuboid bbox={oo.bbox} ours='{oo.name}' bb='{bo.name}'")
            for line in bad:
                print(f"  {line}")

    print("\nSummary")
    print(f"mismatched_faces={mismatched_faces}")
    print(f"- rect_mismatch={rect_mismatch}")
    print(f"- corner_mismatch={corner_mismatch}")

    return mismatched_faces


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ours", required=True, type=Path)
    ap.add_argument("--bb", required=True, type=Path)
    ap.add_argument("--eps-pos", type=float, default=EPS_POS_DEFAULT)
    ap.add_argument("--eps-uv", type=float, default=EPS_UV_DEFAULT)
    ap.add_argument("--max-cuboid-print", type=int, default=-1)
    args = ap.parse_args()

    ours = _parse_obj(args.ours)
    bb = _parse_obj(args.bb)

    mismatches = _compare_objects(
        ours=ours,
        bb=bb,
        eps_pos=float(args.eps_pos),
        eps_uv=float(args.eps_uv),
        max_cuboid_print=int(args.max_cuboid_print),
    )

    return 0 if mismatches == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
